### ISSUE TITLE
Can't open very big file with empty rows

### ISSUE THREAD

**Issue by JWo1F** [KeeTraxx/kexcel#11]
Hi there! I have a very big file (over 1'000'000 lines), but the one have only 4 filled rows. Other rows are empty.
While the file is opening my node process is not responding. It's about several minutes.

**Comment by KeeTraxx** [comment]
Hello and thanks for trying out `kexcel`!

Since `kexcel` processes data from sheets in-memory, it can't conveniently deal with such large rows.

**Comment by JWo1F** [comment]
@KeeTraxx  I think, we need to add something like "maxEmptyRows", what do you think?
