### ISSUE TITLE
I often get corrupt files. Any idea on how to prevent this?

### ISSUE THREAD

**Issue by etiennea** [KeeTraxx/kexcel#3]

**Comment by KeeTraxx** [comment]
Closing issue for being inactive...

**Comment by etiennea** [comment]
I actually use kexell in production as it was the only npm package that would allow me to fill in value to a pre-populated xlsm file with pivot tables etc... I had to use an xlsm script to force the refresh though.

My files where corrupted very often and I think I figured out the issue. What in the inital file, as cell format has been set that is not the default: ie: Date. Then kexcel will corrupt the whole file. Perhaps something could be done that resets the cell to the default type before inserting?

**Comment by KeeTraxx** [comment]
Thank you for your input, I'll have a look into it.

**Comment by KeeTraxx** [comment]
Just to let you know: I did a complete rewrite of kexcel like some days ago.
The fix is only in version 2.0.3. The API has changed a bit too...
