### ISSUE TITLE
Excel doesn't calculate

### ISSUE THREAD

**Issue by Azimuth67** [KeeTraxx/kexcel#8]
Hello!

The script below put 23.4 in cell A4 in korrtermer/ID101_103_2015.xlsx.
I'm trying to read the result of the formula in cell B4.
It seems that excel doesn't care if the value in cell A4 changes.
It presents the previous result.
When I open Excel I can see that A4=23.4 but the calculation is wrong.

What is happening?

```javascript
var kexcel = require('kexcel');
var fs = require('fs');

exports.test = function(req, res){

  kexcel.open( 'korrtermer/ID101_103_2015.xlsx', function(err, workbook) {
 

    var sheet1 = workbook.getSheet(0);

    var x = parseFloat(23.4);

    sheet1.setCellValue(4,1,x,"");
    
    var output = fs.createWriteStream('korrtermer/ID101_103_2015.xlsx');
    workbook.pipe(output);    

  });

  kexcel.open( 'korrtermer/ID101_103_2015.xlsx', function(err, workbook) {
 

    var sheet1 = workbook.getSheet(0);
    console.log(sheet1.getCellValue(4,2));
    res.end();
  });
}
```

**Comment by KeeTraxx** [comment]
Hi there!

I'm afraid kexcel doesn't have a calculation engine of its own. Therefore calculated values are only updated when you open the file in a proper spreadsheet application (e.g. Excel or LibreOffice Calc).
